// icons.js
import {
  SiReact,
  SiNextdotjs,
  SiJavascript,
  SiAmazonaws,
  SiAmazons3,
  SiAmazonapigateway,
  SiAmazoncloudwatch,
  SiAmazondocumentdb,
  SiAmazondynamodb,
  SiAmazonec2,
  SiAmazonecs,
  SiAmazoneks,
  SiAmazon,
  SiAmazonrds,
  SiAmazonredshift,
  SiAmazonroute53,
  SiAnaconda,
  SiAndroid,
  SiAndroidstudio,
  SiAngular,
  SiAnsible,
  SiApache,
  SiApacheairflow,
  SiApachecassandra,
  SiApachecloudstack,
  SiApachecouchdb,
  SiApachedruid,
  SiApacheflink,
  SiApachehadoop,
  SiApachehive,
  SiApachekafka,
  SiApachemaven,
  SiApachespark,
  SiApachestorm,
  SiApachetomcat,
  SiArchlinux,
  SiArduino,
  SiArgo,
  SiAwslambda,
  SiBitbucket,
  SiBitcoin,
  SiBlender,
  SiBootstrap,
  SiBun,
  SiCelery,
  SiChakraui,
  SiCloudflare,
  SiCmake,
  SiCockroachlabs,
  SiConfluence,
  SiCss3,
  SiDaisyui,
  SiDart,
  SiDatabricks,
  SiDeno,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiElasticsearch,
  SiElectron,
  SiElixir,
  SiFastapi,
  SiFedora,
  SiFigma,
  SiFirebase,
  SiFlask,
  SiFlutter,
  SiGit,
  SiGitbook,
  SiGithub,
  SiGnu,
  SiGo,
  SiGooglebigquery,
  SiGooglecolab,
  SiGooglecloud,
  SiGradle,
  SiGrafana,
  SiGraphql,
  SiGunicorn,
  SiHeroku,
  SiHibernate,
  SiHugo,
  SiInfluxdb,
  SiIntellijidea,
  SiJirasoftware,
  SiJquery,
  SiJson,
  SiJunit5,
  SiK3S,
  SiKibana,
  SiKotlin,
  SiKubernetes,
  SiLaravel,
  SiLinux,
  SiMaterialdesign,
  SiMongodb,
  SiMysql,
  SiNginx,
  SiNodedotjs,
  SiNotion,
  SiNuxtdotjs,
  SiOpencv,
  SiOpengl,
  SiOpenjdk,
  SiPhp,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPrometheus,
  SiPydantic,
  SiPython,
  SiPytorch,
  SiQt,
  SiRabbitmq,
  SiRaspberrypi,
  SiReactquery,
  SiRedis,
  SiRedux,
  SiRemix,
  SiRuby,
  SiRubyonrails,
  SiRust,
  SiScala,
  SiScikitlearn,
  SiSketch,
  SiSnowflake,
  SiSolid,
  SiSpring,
  SiSpringboot,
  SiSpringsecurity,
  SiSqlite,
  SiStorybook,
  SiSupabase,
  SiSuse,
  SiSvelte,
  SiSwagger,
  SiSwift,
  SiTailwindcss,
  SiTensorflow,
  SiTerraform,
  SiThreedotjs,
  SiTypescript,
  SiUbuntu,
  SiVercel,
  SiVim,
  SiVite,
  SiVuedotjs,
  SiWebgl,
  SiXamarin,
} from 'react-icons/si';

export type IconOption = {
  value: string;
  label: string;
};

export const icons = {
  Amazon: SiAmazon,
  AmazonAWS: SiAmazonaws,
  AmazonS3: SiAmazons3,
  AmazonAPIGateway: SiAmazonapigateway,
  AmazonCloudWatch: SiAmazoncloudwatch,
  AmazonDocumentDB: SiAmazondocumentdb,
  AmazonDynamoDB: SiAmazondynamodb,
  AmazonEC2: SiAmazonec2,
  AmazonECS: SiAmazonecs,
  AmazonEKS: SiAmazoneks,
  AmazonRDS: SiAmazonrds,
  AmazonRedShift: SiAmazonredshift,
  AmazonRoute53: SiAmazonroute53,
  Anaconda: SiAnaconda,
  Android: SiAndroid,
  AndroidStudio: SiAndroidstudio,
  Angular: SiAngular,
  Ansible: SiAnsible,
  Apache: SiApache,
  ApacheAirflow: SiApacheairflow,
  ApacheCassandra: SiApachecassandra,
  ApacheCloudStack: SiApachecloudstack,
  ApacheCouchDB: SiApachecouchdb,
  ApacheDruid: SiApachedruid,
  ApacheFlink: SiApacheflink,
  ApacheHadoop: SiApachehadoop,
  ApacheHive: SiApachehive,
  ApacheKafka: SiApachekafka,
  ApacheMaven: SiApachemaven,
  ApacheSpark: SiApachespark,
  ApacheStorm: SiApachestorm,
  ApacheTomcat: SiApachetomcat,
  ArchLinux: SiArchlinux,
  Arduino: SiArduino,
  Argo: SiArgo,
  AWSLanbda: SiAwslambda,
  BitBucket: SiBitbucket,
  Bitcoin: SiBitcoin,
  Blender: SiBlender,
  Bootstrap: SiBootstrap,
  Bun: SiBun,
  Celery: SiCelery,
  ChakraUi: SiChakraui,
  CloudFlare: SiCloudflare,
  Cmake: SiCmake,
  CockroachDB: SiCockroachlabs,
  Confluence: SiConfluence,
  CSS3: SiCss3,
  DaisyUi: SiDaisyui,
  Dart: SiDart,
  Databricks: SiDatabricks,
  Deno: SiDeno,
  Django: SiDjango,
  Docker: SiDocker,
  '.Net': SiDotnet,
  ElasticSearch: SiElasticsearch,
  Electron: SiElectron,
  Elixir: SiElixir,
  FastAPI: SiFastapi,
  Fedora: SiFedora,
  Figma: SiFigma,
  FireBase: SiFirebase,
  Flask: SiFlask,
  Flutter: SiFlutter,
  Git: SiGit,
  Gitbook: SiGitbook,
  Github: SiGithub,
  GNU: SiGnu,
  Go: SiGo,
  BigQuery: SiGooglebigquery,
  GoogleColab: SiGooglecolab,
  GoogleCloud: SiGooglecloud,
  Gradle: SiGradle,
  Grafana: SiGrafana,
  GraphQL: SiGraphql,
  Gunicorn: SiGunicorn,
  Heroku: SiHeroku,
  Hibernate: SiHibernate,
  Hugo: SiHugo,
  InfluxDB: SiInfluxdb,
  IntellijIDEA: SiIntellijidea,
  JavaScript: SiJavascript,
  Jira: SiJirasoftware,
  Jquery: SiJquery,
  JSON: SiJson,
  Junit5: SiJunit5,
  K3S: SiK3S,
  Kibana: SiKibana,
  Kotlin: SiKotlin,
  Kubernetes: SiKubernetes,
  Laravel: SiLaravel,
  Linux: SiLinux,
  MaterialDesign: SiMaterialdesign,
  MongoDB: SiMongodb,
  MySQL: SiMysql,
  'Next.js': SiNextdotjs,
  Nginx: SiNginx,
  'Node.js': SiNodedotjs,
  Notion: SiNotion,
  'Nuxt.js': SiNuxtdotjs,
  OpenCV: SiOpencv,
  OpenGL: SiOpengl,
  OpenJDK: SiOpenjdk,
  PHP: SiPhp,
  PostgreSQL: SiPostgresql,
  Postman: SiPostman,
  Prisma: SiPrisma,
  Prometheus: SiPrometheus,
  Pydantic: SiPydantic,
  Python: SiPython,
  Pytorch: SiPytorch,
  Qt: SiQt,
  RabbitMQ: SiRabbitmq,
  RaspberryPi: SiRaspberrypi,
  React: SiReact,
  ReactQuery: SiReactquery,
  Redis: SiRedis,
  Redux: SiRedux,
  Remix: SiRemix,
  Ruby: SiRuby,
  RubyOnRails: SiRubyonrails,
  Rust: SiRust,
  Scala: SiScala,
  ScikitLearn: SiScikitlearn,
  Sketch: SiSketch,
  SnowFlake: SiSnowflake,
  Solid: SiSolid,
  Spring: SiSpring,
  SpringBoot: SiSpringboot,
  SpringSecurity: SiSpringsecurity,
  SQLite: SiSqlite,
  StoryBook: SiStorybook,
  SupaBase: SiSupabase,
  Suse: SiSuse,
  Svelte: SiSvelte,
  Swagger: SiSwagger,
  Swift: SiSwift,
  TailwindCSS: SiTailwindcss,
  TensorFlow: SiTensorflow,
  Terraform: SiTerraform,
  'Three.js': SiThreedotjs,
  TypeScript: SiTypescript,
  Ubuntu: SiUbuntu,
  Vercel: SiVercel,
  Vim: SiVim,
  Vite: SiVite,
  'Vue.js': SiVuedotjs,
  WebGL: SiWebgl,
  Xamarin: SiXamarin,
  // 추가 아이콘
};
